export enum StorageKeys {
  JWT = 'JWT',
  USER_TYPE = 'USER_TYPE',
  USER_STATUS = 'USER_STATUS',
  USER_EMAIL = 'USER_EMAIL',
  USER_PASSWORD = 'USER_PASSWORD',
  FORGOT_PASSWORD_EMAIL = 'FORGOT_PASSWORD_EMAIL',
  FORGOT_PASSWORD_CODE = 'FORGOT_PASSWORD_CODE',
  PERSONAL_INFO = 'PERSONAL_INFO',
  SIGNUP = 'SIGNUP',
  FIRSTACCESS = 'FIRSTACCESS',
  SMS_CODE = "SMS_CODE",
}
